---
services: docker

before_install:
  # Upgrade Docker.
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce

script:
  - docker-compose -f ubuntu.yml build foscal
  - docker container run --rm -v /var/run/docker.sock:/var/run/docker.sock aquasec/trivy finaldes/docker-ubuntu-ansible:foscal
  - docker-compose -f ubuntu.yml up -d foscal
  - docker-compose -f ubuntu.yml exec -T foscal python3 --version
  - docker-compose -f ubuntu.yml exec -T foscal ansible --version
  - docker-compose -f ubuntu.yml exec -T foscal sudo -u ansible sudo -v
  - docker-compose -f ubuntu.yml down
  # # Test building Dockerfile.
  # - docker build -t docker-ansible .

  # # Test running the container.
  # - docker run --name test-container -d --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro docker-ansible

  # # Verify that `ansible` user exists and is a sudoer
  # - docker exec --tty test-container env TERM=xterm sudo -u ${ANSIBLE_USER} sudo -v

  # # Verify Ansible is available in the container.
  # - docker exec --tty test-container env TERM=xterm ansible --version
