---
services: docker

before_install:
  # Upgrade Docker.
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce

script:
  - docker-compose build ubuntu-foscal
  - docker-compose up -d ubuntu-foscal
  - docker-compose exec -T ubuntu-foscal python3 --version
  - docker-compose exec -T ubuntu-foscal ansible --version
  - docker-compose exec -T ubuntu-foscal sudo -u ansible sudo -v
  - docker-compose down
  # # Test building Dockerfile.
  # - docker build -t docker-ansible .

  # # Test running the container.
  # - docker run --name test-container -d --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro docker-ansible

  # # Verify that `ansible` user exists and is a sudoer
  # - docker exec --tty test-container env TERM=xterm sudo -u ${ANSIBLE_USER} sudo -v

  # # Verify Ansible is available in the container.
  # - docker exec --tty test-container env TERM=xterm ansible --version
