version: '2.4'
x-base: &base
  volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup:ro
  privileged: true
services:
  xenial:
    <<: *base
    build:
      context: .
      dockerfile: ubuntu/16.04/Dockerfile
    image: finaldes/docker-ubuntu-ansible:bionic
  bionic:
    <<: *base
    build:
      context: .
      dockerfile: ubuntu/18.04/Dockerfile
    image: finaldes/docker-ubuntu-ansible:bionic
  foscal:
    <<: *base
    build:
      context: .
      dockerfile: ubuntu/20.04/Dockerfile
    image: finaldes/docker-ubuntu-ansible:foscal