version: '2.4'
services:
  xenial:
    build:
      context: .
      dockerfile: ubuntu/16.04/Dockerfile
    image: finaldes/docker-ubuntu-ansible:bionic
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
  bionic:
    build:
      context: .
      dockerfile: ubuntu/18.04/Dockerfile
    image: finaldes/docker-ubuntu-ansible:bionic
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
  foscal:
    build:
      context: .
      dockerfile: ubuntu/20.04/Dockerfile
    image: finaldes/docker-ubuntu-ansible:foscal
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true