x-base: &base
  volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup:ro
  privileged: true
services:
  xenial:
    <<: *base
    build:
      context: .
      dockerfile: ubuntu/xenial/Dockerfile
    image: finaldes/docker-ubuntu-ansible:xenial
  bionic:
    <<: *base
    build:
      context: .
      dockerfile: ubuntu/bionic/Dockerfile
    image: finaldes/docker-ubuntu-ansible:bionic
  focal:
    <<: *base
    build:
      context: .
      dockerfile: ubuntu/focal/Dockerfile
    image: finaldes/docker-ubuntu-ansible:focal
  jammy:
    <<: *base
    build:
      context: .
      dockerfile: ubuntu/jammy/Dockerfile
    image: finaldes/docker-ubuntu-ansible:jammy
  noble:
    <<: *base
    build:
      context: .
      dockerfile: ubuntu/noble/Dockerfile
    image: finaldes/docker-ubuntu-ansible:noble
