name: docker build

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
      - develop
      - test
      - create-workflow/*
jobs:
  test:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        build-os:
          - ubuntu-xenial
          - ubuntu-bionic
          - ubuntu-foscal
        os:
          - ubuntu-18.04
    # env:
    #   ANSIBLE_USER: ansible
      # COMPOSE_INTERACTIVE_NO_CLI: "1" #fix the input device is not a TTY
    steps:
      - uses: actions/checkout@v2.1.0
      - name: check docker compose version
        run: docker-compose --version
      - name: build image ubuntu ${{matrix.build-os}} -t
        run: docker-compose build ${{matrix.build-os}}
      - name: list docker image
        run: docker image ls
      - name: run container
        run: docker-compose up -d ${{matrix.build-os}}
      - name: check python version
        run: docker-compose exec -T ${{matrix.build-os}} python3 --version
      - name: check ansible
        run: docker-compose exec -T ${{matrix.build-os}} ansible --version
      - name: ansible user
        run:  docker-compose exec -T ${{matrix.build-os}} sudo -u ansible sudo -v
      - name: destroy the container 
        run: docker-compose down
      