name: Ubuntu 18.04 build

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
      - develop
      - test
      - create-workflow/*
jobs:
  test:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os:
          - ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.1.0
      - name: build image ubuntu 18.04
        run: docker-compose build -f ubuntu/18.04/Dockerfile
      - name: check python version
        run: docker-compose exec ubuntu-bionic python3 --version