name: Ubuntu 18.04 build

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
      - develop
      - test
      - create-workflow/*
jobs:
  test:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os:
          - ubuntu-18.04
    env:
      COMPOSE_INTERACTIVE_NO_CLI: "1" #fix the input device is not a TTY
    steps:
      - uses: actions/checkout@v2.1.0
      - name: check docker compose version
        run: docker-compose --version
      - name: build image ubuntu 18.04
        run: docker-compose build
      - name: run container
        run: docker-compose up -d
      - name: check python version
        run: docker-compose exec ubuntu-bionic python3 --version
      - name: destroy the container 
        run: docker-compose down